In [17]:
import pandas as pd
import numpy as np

col_names = [
    'Sample code number', 'Clump Thickness', 'Uniformity of Cell Size',
    'Uniformity of Cell Shape', 'Marginal Adhesion',
    'Single Epithelial Cell Size', 'Bare Nuclei',
    'Bland Chromatin', 'Normal Nucleoli', 'Mitoses', 'Class'
]

df = pd.read_csv('data/breast-cancer-wisconsin.data',
                 names=col_names,
                 na_values='?')
df.head()

,Sample code number,Clump Thickness,Uniformity of Cell Size,Uniformity of Cell Shape,Marginal Adhesion,Single Epithelial Cell Size,Bare Nuclei,Bland Chromatin,Normal Nucleoli,Mitoses,Class
0,1000025,5,1,1,1,2,1.0,3,1,1,2
1,1002945,5,4,4,5,7,10.0,3,2,1,2
2,1015425,3,1,1,1,2,2.0,3,1,1,2
3,1016277,6,8,8,1,3,4.0,3,7,1,2
4,1017023,4,1,1,3,2,1.0,3,1,1,2


In [19]:
df.fillna(df.median(numeric_only=True), inplace=True)
df = df.drop(columns=['Sample code number'])

In [20]:
proportion_benign = (df['Class'] == 2).sum() / len(df)
print("Proportion Benign:", proportion_benign)

Proportion Benign: 0.6552217453505007


In [22]:
from sklearn.model_selection import train_test_split

X = df.drop(columns=['Class'])  # everything except the answer
y = df['Class']                 # just the answer column

X_train, X_test, y_train, y_test = train_test_split(
    X, y, test_size=0.2, stratify=y, random_state=43
)

print("Train proportion Benign:", (y_train == 2).sum() / len(y_train))
print("Test proportion Benign:", (y_test == 2).sum() / len(y_test))

Train proportion Benign: 0.6547406082289803
Test proportion Benign: 0.6571428571428571


In [24]:
from sklearn.linear_model import LogisticRegression

clf = LogisticRegression(max_iter=1000)
clf.fit(X_train, y_train)

print("Class prediction on train set:\n", clf.predict(X_train)[:10])
print("Probability prediction on train set:\n", clf.predict_proba(X_train)[:10, 1])
print("Score on train set:\n", clf.score(X_train, y_train))

print("Class prediction on test set:\n", clf.predict(X_test)[:10])
print("Probability prediction on test set:\n", clf.predict_proba(X_test)[:10, 1])
print("Score on test set:\n", clf.score(X_test, y_test))

Class prediction on train set:
 [4 2 4 2 2 2 2 4 2 2]
Probability prediction on train set:
 [0.99600525 0.00908951 0.99992741 0.00528932 0.02098032 0.00582947
 0.03566504 0.99515453 0.00788556 0.01065907]
Score on train set:
 0.9695885509838998
Class prediction on test set:
 [2 2 2 4 2 4 2 2 2 4]
Probability prediction on test set:
 [0.01747894 0.22504709 0.00699085 0.54019127 0.00152929 0.9986223
 0.33611399 0.01228123 0.00438318 0.99972361]
Score on test set:
 0.9642857142857143


In [25]:
from sklearn.metrics import confusion_matrix

cm_train = confusion_matrix(y_train, clf.predict(X_train))
cm_test = confusion_matrix(y_test, clf.predict(X_test))

print("Confusion matrix train:\n", cm_train)
print("Confusion matrix test:\n", cm_test)

Confusion matrix train:
 [[357   9]
 [  8 185]]
Confusion matrix test:
 [[90  2]
 [ 3 45]]
