In [4]:
import pandas as pd
import numpy as np
from sklearn.linear_model import LogisticRegression
from sklearn.model_selection import train_test_split
from sklearn.metrics import confusion_matrix

# Load data
col_names = [
    'Sample code number', 'Clump Thickness', 'Uniformity of Cell Size',
    'Uniformity of Cell Shape', 'Marginal Adhesion',
    'Single Epithelial Cell Size', 'Bare Nuclei',
    'Bland Chromatin', 'Normal Nucleoli', 'Mitoses', 'Class'
]

df = pd.read_csv('data/breast-cancer-wisconsin.data', 
                 names=col_names, na_values='?')

# Replace missing values with median of that column
df.fillna(df.median(numeric_only=True), inplace=True)

# Drop the ID column — it carries zero medical information
df = df.drop(columns=['Sample code number'])

In [6]:
#Check class proportions
proportion_benign = (df['Class'] == 2).sum() / len(df)
print("Proportion Benign:", proportion_benign)

Proportion Benign: 0.6552217453505007


In [10]:
X = df.drop(columns=['Class'])
y = df['Class']

X_train, X_test, y_train, y_test = train_test_split(
    X, y, test_size=0.2, stratify=y, random_state=43
)

print("Train proportion Benign:", (y_train == 2).sum() / len(y_train))
print("Test proportion Benign:", (y_test == 2).sum() / len(y_test))

Train proportion Benign: 0.6547406082289803
Test proportion Benign: 0.6571428571428571


In [12]:
clf = LogisticRegression(max_iter=1000)
clf.fit(X_train, y_train)

# Predictions
print("Class prediction on train set:\n", clf.predict(X_train)[:10])
print("Probability prediction on train set:\n", clf.predict_proba(X_train)[:10, 1])
print("Score on train set:\n", clf.score(X_train, y_train))

print("Class prediction on test set:\n", clf.predict(X_test)[:10])
print("Probability prediction on test set:\n", clf.predict_proba(X_test)[:10, 1])
print("Score on test set:\n", clf.score(X_test, y_test))

Class prediction on train set:
 [4 2 4 2 2 2 2 4 2 2]
Probability prediction on train set:
 [0.99600525 0.00908951 0.99992741 0.00528932 0.02098032 0.00582947
 0.03566504 0.99515453 0.00788556 0.01065907]
Score on train set:
 0.9695885509838998
Class prediction on test set:
 [2 2 2 4 2 4 2 2 2 4]
Probability prediction on test set:
 [0.01747894 0.22504709 0.00699085 0.54019127 0.00152929 0.9986223
 0.33611399 0.01228123 0.00438318 0.99972361]
Score on test set:
 0.9642857142857143


In [13]:
cm_train = confusion_matrix(y_train, clf.predict(X_train))
cm_test = confusion_matrix(y_test, clf.predict(X_test))

print("Confusion matrix train:\n", cm_train)
print("Confusion matrix test:\n", cm_test)

Confusion matrix train:
 [[357   9]
 [  8 185]]
Confusion matrix test:
 [[90  2]
 [ 3 45]]
