In [2]:
import numpy as np
from sklearn.model_selection import train_test_split

# Question 1 — naive split, no shuffle
X = np.arange(1, 21).reshape(10, -1)
y = np.zeros(10)
y[7:] = 1  # only last 3 are class 1

X_train, X_test, y_train, y_test = train_test_split(
    X, y, test_size=0.2, shuffle=False
)

print("X_train:\n", X_train)
print("y_train:\n", y_train)
print("X_test:\n", X_test)
print("y_test:\n", y_test)

print("Proportion class 1 in train:", y_train.sum() / len(y_train))
print("Proportion class 1 in test:", y_test.sum() / len(y_test))

X_train:
 [[ 1  2]
 [ 3  4]
 [ 5  6]
 [ 7  8]
 [ 9 10]
 [11 12]
 [13 14]
 [15 16]]
y_train:
 [0. 0. 0. 0. 0. 0. 0. 1.]
X_test:
 [[17 18]
 [19 20]]
y_test:
 [1. 1.]
Proportion class 1 in train: 0.125
Proportion class 1 in test: 1.0


In [3]:
# Question 2 — stratified split
X = np.arange(1, 201).reshape(100, -1)
y = np.zeros(100)
y[70:] = 1  # 30% are class 1

X_train, X_test, y_train, y_test = train_test_split(
    X, y, test_size=0.2, stratify=y, random_state=43
)

print("Proportion class 1 in train:", y_train.sum() / len(y_train))
print("Proportion class 1 in test:", y_test.sum() / len(y_test))

Proportion class 1 in train: 0.3
Proportion class 1 in test: 0.3
